//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry_Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry_Form()
        {
            this.order_service = new HashSet<order_service>();
            this.order_stkitem = new HashSet<order_stkitem>();
        }
    
        public int Id { get; set; }
        public string plate_no { get; set; }
        public string Brand { get; set; }
        public string Owner_name { get; set; }
        public string phone { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public System.DateTime date { get; set; }
        public string Alpha { get; set; }
		public string region { get; set; }
		public int code { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_service> order_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_stkitem> order_stkitem { get; set; }
    }
}
