//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaragedbEntities : DbContext
    {
        public GaragedbEntities()
            : base("name=GaragedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entry_Form> Entry_Form { get; set; }
        public virtual DbSet<order_service> order_service { get; set; }
        public virtual DbSet<order_stkitem> order_stkitem { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<recipt> recipts { get; set; }
        public virtual DbSet<service_table> service_table { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
