//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int Id { get; set; }
        public double old_quantity { get; set; }
        public double new_quantity { get; set; }
        public double remain_quantity { get; set; }
        public double price { get; set; }
        public double total_price { get; set; }
        public System.DateTime date { get; set; }
        public int StockId { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
