//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipt
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public string customer_Fullname { get; set; }
        public string Plate_no { get; set; }
        public string description { get; set; }
        public double quantity { get; set; }
        public double price { get; set; }
        public double total { get; set; }
        public double vat { get; set; }
        public double tot_withvat { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> EntryFormId { get; set; }
        public string Alpha { get; set; }
    }
}
