//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phone_no { get; set; }
        public string role { get; set; }
        public bool status { get; set; }
        public string ResetPasswordCode { get; set; }
    }
    public enum role
    {
        Mechanic,Admin,Cashier,StockManager
    }
    public enum gender
    {
        Male,Female
    }
    public enum region
    {
        Amh,AA,Oro
    }
    public enum code
    {
        P,C,G
    } 
    public enum Alpa
    {
        A,B,C
    }
}
